steps:
  # Step 1: Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/ai-autograder-image', '.']

  # Step 2: Push the image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/ai-autograder-image']

  # Step 3: Deploy the new image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'ai-in-education-project-rideruniversity-csc360'
      - '--image'
      - 'gcr.io/$PROJECT_ID/ai-autograder-image'
      - '--region'
      - 'us-central1'
      - '--allow-unauthenticated'

images:
  - 'gcr.io/$PROJECT_ID/ai-autograder-image'

options:
  logging: CLOUD_LOGGING_ONLY